parameters:
#    tum_ventureinitiative_test.example.class: TUM\Ventureinitiative\TestBundle\Example

services:
#    tum_ventureinitiative_test.example:
#        class: %tum_ventureinitiative_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
