parameters:
    tum_ventureinitiative_test.test_manager.class: TUM\Ventureinitiative\TestBundle\Services\TestManager

services:
    tum_ventureinitiative_test.test_manager:
        class: %tum_ventureinitiative_test.test_manager.class%
        calls:
            - [ setContainer, [@service_container] ]