<?php

namespace TUM\Ventureinitiative\UserManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

	public function paging($page = 1, $entries = 10) {
		
		$dqlPaging = "SELECT u FROM UserManagementBundle:User u";
		$dqlCount = "SELECT COUNT(u) FROM UserManagementBundle:User u";
		
		$page--;
		
		$query = $this->getEntityManager()
			->createQuery($dqlPaging)
			->setFirstResult($page * $entries)
			->setMaxResults($entries);
		
		$paginator = new Paginator($query, $fetchJoinCollection = true);
		
		$users = array();
		
		foreach($paginator as $user) {
			
			$users[] = $user;
			
		}
		
		$pageCount = ceil(count($this->getEntityManager()->getRepository('UserManagementBundle:User')->findAll()) / $entries);
		
		return array('users' => $users, 'pageCount' => $pageCount); 
		
	}
	
}
