parameters:
    tum_ventureinitiative_group.mailer.class: TUM\Ventureinitiative\GroupBundle\Controller\MailController

services:
    tum_ventureinitiative_group.mailer:
        class: %tum_ventureinitiative_group.mailer.class%
        calls:
            - [ setContainer, [@service_container] ]
